# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  - azureml-core
  - azureml-defaults
  - azureml-telemetry
  - azureml-train-restclients-hyperdrive
  - azureml-train-core
  - azureml-widgets
  - azureml-pipeline-core
  - azureml-pipeline-steps
  - azureml-opendatasets
  - azureml-automl-core
  - azureml-automl-runtime
  - azureml-train-automl-client
  - azureml-train-automl-runtime
  - azureml-train-automl
  - azureml-train
  - azureml-interpret
  - azureml-tensorboard
  - azureml-mlflow
  - azureml-contrib-services
  - mlflow
  - sklearn-pandas
  - azureml==0.2.7
  - numpy
  - onnxruntime
  - pandas
  - joblib==0.14.1
  - azureml-model-management-sdk
  - azureml-sdk
  - onnx
channels:
- anaconda
- conda-forge
